name: Automação das previsões

on:
  push:
    branches: [ 'main' ]
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:


jobs:
  Modelagem:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3

      - name: Instalar pacotes Python
        run: poetry install --no-root

      - name: Atualizar previsões
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          poetry config virtualenvs.prefer-active-python true
          poetry run python 06-ipca.py
          poetry run python -c "exec('import time;time.sleep(61)')"
          poetry run python 07-cambio.py
          poetry run python -c "exec('import time;time.sleep(61)')"
          poetry run python 08-pib.py
          poetry run python -c "exec('import time;time.sleep(61)')"
          poetry run python 09-selic.py

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Atualização automática de previsões
